import Head from "next/head";
import dynamic from "next/dynamic";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { useEffect, useState } from "react";
import { RealtimeChannel } from "@supabase/supabase-js";
import { BlockNoteEditor } from "@blocknote/core";
import { concat } from "lodash";
import { P, match } from "ts-pattern";

const Editor = dynamic(() => import("../components/Editor"), { ssr: false });

const emojis = ["👍", "🤔", "🌟"]; // Your emoji list

export default function Home() {
  const supabase = useSupabaseClient();
  const [channel] = useState<RealtimeChannel>(() =>
    supabase.channel("realtime:test")
  );
  const [selectedEmoji, setSelectedEmoji] = useState(""); // New state variable for the selected emoji
  const [textCursorBlockId, setTextCursorBlockId] = useState<string | null>(
    null
  );
  const [emojiBlockId, setEmojiBlockId] = useState<string | null>();

  const [editor, setEditor] = useState<BlockNoteEditor | null>(null);

  const handleEditorReady = (editor: BlockNoteEditor | null) => {
    console.log("handleEditorReady");
    setEditor(editor);
  };

  useEffect(() => {
    channel
      .on("broadcast", { event: "emoji" }, (payload) => {
        match(payload)
          .with(
            {
              event: "emoji",
              payload: {
                emoji: P.string,
              },
            },
            (payload) => {
              console.log("broadcast", payload);
              setSelectedEmoji(payload.payload.emoji);
            }
          )
          .otherwise(() => console.log("otherwise"));
      })
      .subscribe();
  }, []);

  const handleEmojiClick = (emoji: string) => {
    channel
      .send({
        type: "broadcast",
        event: "emoji",
        payload: {
          emoji,
        },
      })
      .catch(console.error);
    console.log(`You clicked on ${emoji}`);
    setSelectedEmoji(emoji); // update the selectedEmoji when an emoji is clicked
    setEmojiBlockId(textCursorBlockId);
    if (textCursorBlockId) {
      const block = editor?.getBlock(textCursorBlockId);
      if (block) {
        editor?.updateBlock(textCursorBlockId, {
          content: concat(
            { type: "text", text: emoji, styles: {} },
            block.content
          ),
        });
      }
    }
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="w-full">
          <div className="flex justify-center">
            {emojis.map((emoji, index) => (
              <button
                key={index}
                onClick={() => handleEmojiClick(emoji)}
                className="emoji-button mx-2 rounded-lg p-2 shadow-md"
                style={{ fontSize: "1.5em" }}
              >
                {emoji}
              </button>
            ))}
          </div>
          <div className="border-2">
            <Editor
              selectedEmoji={selectedEmoji}
              onEditorReady={handleEditorReady}
              setTextCursorBlockId={setTextCursorBlockId}
            />
          </div>
          <div className="mt-4">Received emoji: {selectedEmoji}</div>{" "}
          <div>textCursorBlockId: {textCursorBlockId}</div>
          <div>emojiBlockId: {emojiBlockId}</div>
        </div>
      </main>
    </>
  );
}
